# Descriptive Implementation of ANN using PyTorch

Importing Libraries

In [2]:
import torch

Sigmoid Function

In [3]:
sigmoid = torch.sigmoid

Initialize Weights and Biases

In [4]:
# Input (3) -> Hidden Layer 1 (4)
W1 = torch.rand(3, 4)
b1 = torch.rand(1, 4)

# Hidden Layer 1 (4) -> Hidden Layer 2 (4)
W2 = torch.rand(4, 4)
b2 = torch.rand(1, 4)

# Hidden Layer 2 (4) -> Output (1)
W3 = torch.rand(4, 1)
b3 = torch.rand(1, 1)


Initial Value 

In [5]:
X = torch.tensor([[0.5, 0.8, 0.2]])

Feed Forward

In [6]:
# Hidden Layer 1
H1 = sigmoid(torch.matmul(X, W1) + b1)

# Hidden Layer 2
H2 = sigmoid(torch.matmul(H1, W2) + b2)

# Output Layer
Y = sigmoid(torch.matmul(H2, W3) + b3)

Display Result

In [7]:
print("Input:")
print(X)

print("\nHidden Layer 1:")
print(H1)

print("\nHidden Layer 2:")
print(H2)

print("\nOutput:")
print(Y)

Input:
tensor([[0.5000, 0.8000, 0.2000]])

Hidden Layer 1:
tensor([[0.8071, 0.6574, 0.8174, 0.7780]])

Hidden Layer 2:
tensor([[0.8720, 0.9194, 0.8486, 0.9239]])

Output:
tensor([[0.9223]])
