Basics 
* Condition
* Loop
* Function 
* List 
* Numpy 

Please don't go through its complexities as these are only written for syntax revision so these are not the efficent ones 

In [3]:
x = 89 
semaphore = 0
for i in range(x):
    if i*i == x:
        print("It has an squre root")
        semaphore = 1
if semaphore == 0:
    print("There is no perfect sqare root")

There is no perfect sqare root


In [7]:
import time
times = 10 
for i in range(times, 0 , -1):
    print(f"The remaining time is", i)
    if i < 4: 
        time.sleep(0.5)
    else:
        time.sleep(1)
print("BOOOMMMMMMM  🚀")

The remaining time is 10
The remaining time is 9
The remaining time is 8
The remaining time is 7
The remaining time is 6
The remaining time is 5
The remaining time is 4
The remaining time is 3
The remaining time is 2
The remaining time is 1
BOOOMMMMMMM  🚀


In [11]:
import numpy as np
def fibo(n):
    k = 1/ np.sqrt(5)
    j = ((1 + np.sqrt(5))/2)**n
    l = ((1 - np.sqrt(5))/2)**n
    return int(k*(j-l))

In [13]:
print(fibo(55))

139583862445


In [18]:
arr = [2,56,23,7,2345,67,2,4,66,1,9]
for i in range(0, len(arr)-1):
    if arr[i]<10:
        arr[i] = arr[i]*3
    if arr[i]>100:
        arr.pop(i)
arr
    

[6, 56, 23, 21, 67, 6, 12, 66, 3, 27]

NumPy Linear Algebra  

In [19]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

Matrix Multiplication

In [20]:
A@A

array([[42, 12, 18],
       [26, 48, 29],
       [58, 42, 91]])

Transpose

In [21]:
A.T

array([[ 6,  4,  2],
       [ 1, -2,  8],
       [ 1,  5,  7]])

Trace (Sum of Diagonals)

In [22]:
np.trace(A)

11

Inverse of a Matrix

In [23]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

Determininet of a Matrix

In [24]:
np.linalg.det(A)

-306.0

Rank of a Matrix

In [25]:
np.linalg.matrix_rank(A)

3

In [26]:
v = np.array([3,4,7,2,7])
np.dot(v,v)

127