# Detailed Implementation of Feed Forward ANN using NumPy

Importing Libraries 

In [1]:
import numpy as np

Sigmoid Function

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Initialize Weights and Biases

In [3]:
# Input (3) -> Hidden Layer 1 (4)
W1 = np.random.rand(3, 4)
b1 = np.random.rand(1, 4)

# Hidden Layer 1 (4) -> Hidden Layer 2 (4)
W2 = np.random.rand(4, 4)
b2 = np.random.rand(1, 4)

# Hidden Layer 2 (4) -> Output (1)
W3 = np.random.rand(4, 1)
b3 = np.random.rand(1, 1)

Imput Value

In [4]:
X = np.array([[0.5, 0.8, 0.2]]) 

Feed Forward

In [5]:
# Hidden Layer 1
H1 = sigmoid(np.dot(X, W1) + b1)

# Hidden Layer 2
H2 = sigmoid(np.dot(H1, W2) + b2)

# Output Layer
Y = sigmoid(np.dot(H2, W3) + b3)

Evolution of values

In [6]:
print("Input:")
print(X)

print("\nHidden Layer 1:")
print(H1)

print("\nHidden Layer 2:")
print(H2)

print("\nOutput:")
print(Y)

Input:
[[0.5 0.8 0.2]]

Hidden Layer 1:
[[0.85294297 0.67434609 0.77002378 0.79188343]]

Hidden Layer 2:
[[0.92848293 0.87257644 0.85962992 0.89280451]]

Output:
[[0.77944163]]
