# Descriptive Implentation of Fit Forward ANN

The basic structure of the ANN includes requires multiple muliplication of input layers with the given weights, here the bias is now used in this implementation. And for the last layer the addative sum of is given as output, after that we can use sigmoid function to get the value in binary. 

<img src="1.png" alt="Cute Cat" width="900">

Importing required packges for fit forward in ANN

In [34]:
import numpy as np
import matplotlib.pyplot as plt
import random

Enter the number of Inputs and Layers

In [79]:
n = 3 # Inputs
l = 4 # Layers

Input the Input vector here

In [80]:
input_l = [0.3,0.7,0.9] #Input vector
lists = [[0] * n for _ in range(l)]

In [81]:
lists

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

Weight vectors for the layers

In [82]:
for j in range(0,l):
    for i in range(0,n):
        lists[j][i] = round(random.random(), 3)

In [83]:
lists

[[0.659, 0.204, 0.189],
 [0.592, 0.587, 0.373],
 [0.993, 0.608, 0.308],
 [0.468, 0.544, 0.253]]

Values of nodes in every layers

In [84]:
print(input_l)
print("ANN Starts Here")
for i in range(l):
    weight = np.array(lists[i])
    value = np.array(input_l)
    input_l = weight * value
    print(input_l)

[0.3, 0.7, 0.9]
ANN Starts Here
[0.1977 0.1428 0.1701]
[0.1170384 0.0838236 0.0634473]
[0.11621913 0.05096475 0.01954177]
[0.05439055 0.02772482 0.00494407]


Last layer where the nodes marge into one

In [85]:
last_layer = np.array(input_l)

weights = np.random.rand(len(last_layer))

output = np.dot(weights, last_layer)

In [86]:
round(output, 4)

0.0199